### ISSUE TITLE
fab stage -- does not actually restart uwsgi server

### ISSUE THREAD

**Issue by halfak** [wiki-ai/ores-wikimedia-config#29]
The fab file runs `sudo service uwsgi-ores-web restart`

But there's no service called uwsgi-ores-web so the command just exists immediately. 

Running `sudo service uwsgi restart` works great.

**Comment by yuvipanda** [comment]
hmm, so what had happened is that the 'service uwsgi start' started up the _default_ uwsgi server, which apparently bound to the ports that uwsgi-ores-web was using. The default init script also has a bug in that when killed it never goes away, but keeps locked on to the older one. So what I think happened is that at some point service uwsgi restart was done when uwsgi-ores-web was down, and it started back up and had old stale code running in zombie mode that never was collected. This might also explain why everything worked fine in staging earlier? 

I definitely see a uwsgi-ores-web service - I just stopped the uwsgi one and started ithe more specific one back up. Don't do service uwsgi anything, will just cause issues :) Perhaps I should find ways to get rid of it...

Can you paste the full output from the fabfile?

**Comment by halfak** [comment]
I see.  That makes sense.   I don't have the old output handy anymore.  

I'm going to close this since it's invalid, user error.  I'm sure I ran "sudo service uwsgi restart" at some point and got us into the bad state.
