### ISSUE TITLE
Disable NFS everywhere!

### ISSUE THREAD

**Issue by yuvipanda** [wiki-ai/ores-wikimedia-config#3]
Makes everything better

**Comment by yuvipanda** [comment]
I see a bunch of stuff in /data/project, @halfak can you clean those up?

**Comment by halfak** [comment]
{{done}}

**Comment by yuvipanda** [comment]
So I've disabled both /data/project/ and /home but only for new instances - currently running instances will continue to have them until manually removed. Wheee.

**Comment by yuvipanda** [comment]
I'm going to also delete ores-staging, ores-web-**, ores-redis-01 and ores-lb, and recreate them from scratch tomorrow, NFS free

**Comment by yuvipanda** [comment]
All deletions done
